### ISSUE TITLE
Recall History VIN Decode Failure

### ISSUE THREAD

**Issue by mikecousins** [ClutchEngineering/Sidecar#37]
Our Toyota Sienna shows an error while deciding the VIN for the recall history.

**Comment by monty23monty** [comment]
I have the same issue - Failed to decode VIN U5YH2519LKL016670 with error: 1 - Check Digit (9th position) does not calculate properly; 8 - No detailed data available currently; 400 - Invalid Characters Present

**Comment by jverkoey** [comment]
@monty23monty and @mikecousins, which countries are your cars from? If you're ok with sharing me the first 12 digits of your VIN + the make/model/year of your car, I'll incorporate those into the offline VIN decoder built into Sidecar.

**Comment by mikecousins** [comment]
5TDGSKFC3RS1

2024 Toyota Sienna XSE AWD

**Comment by monty23monty** [comment]
@jverkoey My car was made in Sweden but for the UK - 2018 Kia Ceed Sedan - 5DR 5P

**Comment by jverkoey** [comment]
Thank you both! Incorporating those details into the decoder now and will go out in the next Sidecar release.

**Comment by jverkoey** [comment]
Ok both VINs now successfully decode in Sidecar and this improvement will go out in the next Sidecar release, likely later this week :)
