### ISSUE TITLE
Map Zoom Level

### ISSUE THREAD

**Issue by mattingg** [ClutchEngineering/Sidecar#42]
Not sure if it’s a bug or not, but Sidecar resets the map’s zoom level upon restarting the app/CarPlay, is it possible to have it remember the previous zoom level after a restart?😁

**Comment by jverkoey** [comment]
That's a pretty reasonable expectation :) Adding now.

**Comment by mattingg** [comment]
Sorry to be a pain, I believe the toggle for ‘north’ also resets upon a restart, i appreciate you looking into these things 😁

**Comment by jverkoey** [comment]
Nah these are valid fine tunings; thanks for bringing them up! Feedback like this is what makes the Sidecar hum :)

**Comment by jverkoey** [comment]
Altitude is now remembered across CarPlay connections.

![Main-VideoStream-2024-11-11-19-09-35](https://github.com/user-attachments/assets/fdb2331c-d8e5-44bc-8eaa-ab07b1dc170f)

Will go out in the release I'm cutting tonight.

**Comment by jverkoey** [comment]
Orientation lock will now also be remembered across CarPlay connections ❤️
