### ISSUE TITLE
i4 battery %

### ISSUE THREAD

**Issue by Quantumlyy** [ClutchEngineering/Sidecar#43]
All battery related values on the i4 show that they’re working yet display 0%

**Comment by jverkoey** [comment]
Hey @Quantumlyy! We're actively onboarding the i4 right now; only the speed and odometer parameters appear to be working for sure at this point. I've left some next steps that I need ran on an i4 in https://meta.cars.forum/viewtopic.php?t=146&start=10 — I believe you're already registered on the forums there, so let's continue the discussion there as we onboard the car! I've removed the i4 battery % parameters + support from the matrix for now while we're still onboarding the car.
