### ISSUE TITLE
Apple Watch app unavailable

### ISSUE THREAD

**Issue by DantasticFour** [ClutchEngineering/Sidecar#65]
The SideCar app (not ElectricSideCar app) doesn’t appear as an option to enable/install in the iOS Watch app. 

Is the Series 3 watch compatible with the app, and if so is there a workaround to force install/enable it on the watch?

**Comment by jverkoey** [comment]
Unfortunately the series 3 is no longer supported by Apple and by proxy no longer supported by Sidecar. I don’t believe there’s any way to side load apps onto it unfortunately.

**Comment by DantasticFour** [comment]
Thanks for the quick reply


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
